version: "3.9"
services:
  web:
    depends_on:
      - db
    build:
      dockerfile: ./Dockerfile
      context: .
    tty: true
    stdin_open: true
    command: ./build/cmd/start.sh
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWD: example
      POSTGRES_HOST: db
    ports:
      - 3000:3000

  db:
    image: postgres:alpine3.15
    environment:
      POSTGRES_PASSWORD: example
